name: Integration testing
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Integration testing
        run: |
          docker-compose up --exit-code-from jrest --quiet-pull
      - name: Upload lightning log
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          path: |
            build/reports/tests/test/
          name: jrest-${{ github.run_number }}
